countries=("India","USA","Canada")
temp=list(countries)
temp.append("italy")
temp.pop(1)
countries=tuple(temp)
print(countries)
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]     
print(l1+l2)
res=countries.count("India")
print(res)
